#!/bin/bash
#
# rnexusd startup script for rnexus sinatra server.
# description: Starts Sinatra as an unprivileged user.
#
	 
sudo -u www-data ruby -I/var/www/rnexus/lib /var/www/rnexus/bin/rnexus $1
RETVAL=$?
	 
exit $RETVAL
