#!/bin/bash
#
# rnexusd startup script for rnexus sinatra server.
# description: Starts Sinatra as an unprivileged user.
#
# expects the sinatra app in the directory /home/pi/rnexus
#
# Copy this script to /etc/init.d/
#
# Tell debian to start your daemon when the computer starts up and shut it off 
# when the computer starts down: sudo update-rc.d rnexusd defaults
#
# Start the service manually for your first and only time: 
# sudo /etc/init.d/rnexusd start

# ADJUST this directory to your rnexus source path
APPDIR=/home/pi/rnexus

CTRLSCRIPT=$APPDIR/bin/rnexus

USER=pi
	 
su - $USER -c "$CTRLSCRIPT $1"
RETVAL=$?
	 
exit $RETVAL
