#!/bin/bash
# rnexusd daemon
# chkconfig: 345 20 80
# description: rnexus daemon
# processname: rnexusd

USER="nasarek"
DAEMON_PATH="/home/$USER/Source/rnexus"

DAEMON="bundle exec rake web:run"
DAEMONSTOP="bundle exec rake web:stop"
DEAMONOPTS=""

NAME=rnexusd
DESC="rnexus weather station app daemon"
PIDFILE=$DAEMON_PATH/log/rack.pid
SCRIPTNAME=/etc/init.d/$NAME

case "$1" in
start)
  printf "%-50s" "Starting $NAME..."
  su - $USER -c "cd $DAEMON_PATH;$DAEMON $DAEMONOPTS"
  PID=`cat $PIDFILE` 
        if [ -z $PID ]; then
            printf "%s\n" "Fail"
        else
            printf "%s\n" "Ok"
        fi
;;
status)
        printf "%-50s" "Checking $NAME..."
        if [ -f $PIDFILE ]; then
            PID=`cat $PIDFILE`
            if [ -z "`ps axf | grep ${PID} | grep -v grep`" ]; then
                printf "%s\n" "Process dead but pidfile exists"
            else
                echo "Running"
            fi
        else
            printf "%s\n" "Service not running"
        fi
;;
stop)
        printf "%-50s" "Stopping $NAME"
            PID=`cat $PIDFILE`
        if [ -f $PIDFILE ]; then
            su - $USER -c "cd $DAEMON_PATH;$DAEMONSTOP"
            printf "%s\n" "Ok"
            rm -f $PIDFILE
        else
            printf "%s\n" "pidfile not found"
        fi
;;

restart)
    $0 stop
    $0 start
;;

*)
        echo "Usage: $0 {status|start|stop|restart}"
        exit 1
esac